"""create scan tables

Revision ID: 28e143002457
Revises: 
Create Date: 2026-06-16 10:46:33.281668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28e143002457'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('agent', sa.String(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_logs_id'), 'scan_logs', ['id'], unique=False)
    op.create_index(op.f('ix_scan_logs_run_id'), 'scan_logs', ['run_id'], unique=False)
    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('input', sa.Text(), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_runs_id'), 'scan_runs', ['id'], unique=False)
    op.create_index(op.f('ix_scan_runs_run_id'), 'scan_runs', ['run_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_runs_run_id'), table_name='scan_runs')
    op.drop_index(op.f('ix_scan_runs_id'), table_name='scan_runs')
    op.drop_table('scan_runs')
    op.drop_index(op.f('ix_scan_logs_run_id'), table_name='scan_logs')
    op.drop_index(op.f('ix_scan_logs_id'), table_name='scan_logs')
    op.drop_table('scan_logs')
    # ### end Alembic commands ###
